# universe.py

NIFTY_100 = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "BHARTIARTL.NS", "ICICIBANK.NS",
    "INFY.NS", "ITC.NS", "SBIN.NS", "LICI.NS", "HINDUNILVR.NS",
    "BAJFINANCE.NS", "LT.NS", "HCLTECH.NS", "MARUTI.NS", "SUNPHARMA.NS",
    "KOTAKBANK.NS", "TITAN.NS", "ONGC.NS", "NTPC.NS", "TATAMOTORS.NS",
    "AXISBANK.NS", "ULTRACEMCO.NS", "M&M.NS", "POWERGRID.NS", "ADANIENT.NS",
    "COALINDIA.NS", "BAJAJFINSV.NS", "ASIANPAINT.NS", "ADANIPORTS.NS", "TATASTEEL.NS",
    "JSWSTEEL.NS", "HAL.NS", "SIEMENS.NS", "TRENT.NS", "GRASIM.NS",
    "WIPRO.NS", "TECHM.NS", "SBILIFE.NS", "HDFCLIFE.NS", "BEL.NS",
    "ZOMATO.NS", "PFC.NS", "RECLTD.NS", "BAJAJ-AUTO.NS", "DRREDDY.NS",
    "CIPLA.NS", "NESTLEIND.NS", "HINDALCO.NS", "CHOLAFIN.NS", "DIVISLAB.NS",
    "TORNTPHARM.NS", "LTIM.NS", "EICHERMOT.NS", "TATACONSUM.NS", "APOLLOHOSP.NS",
    "TVSMOTOR.NS", "SHRIRAMFIN.NS", "BOSCHLTD.NS", "INDIGO.NS", "DLF.NS",
    "MAXHEALTH.NS", "AMBUJACEM.NS", "ABB.NS", "CUMMINSIND.NS", "GAIL.NS",
    "IDFCFIRSTB.NS", "JINDALSTEL.NS", "CGPOWER.NS", "POLYCAB.NS", "LUPIN.NS",
    "TIINDIA.NS", "HEROMOTOCO.NS", "MUTHOOTFIN.NS", "BPCL.NS", "UBL.NS",
    "BRITANNIA.NS", "LODHA.NS", "TATACOMM.NS", "SUNDARMFIN.NS", "SRF.NS",
    "PERSISTENT.NS", "IOC.NS", "MCDOWELL-N.NS", "PIIND.NS", "HAVELLS.NS",
    "AUBANK.NS", "BANKBARODA.NS", "PNB.NS", "TATAELXSI.NS", "ASHOKLEY.NS",
    "OBEROIRLTY.NS", "CONCOR.NS", "DIXON.NS", "YESBANK.NS", "IDEA.NS",
    "IRFC.NS", "RVNL.NS", "MAZDOCK.NS", "GMRINFRA.NS", "MOTHERSON.NS"
]

INDEX_TICKER = "^NSEI"  # Nifty 50 Index used as baseline for Relative Strength
